const availableDisplay = {
  HIERARCHY_ONE:1,
  HIERARCHY_TWO:2,
  HIERARCHY_THREE:3,
  HIERARCHY_FOUR:4,
  BREAKING_NEWS:5,
  SPONSORED_CONTENT:6,
  OPINION:7,
  SURVEY:8,
  HIERARCHY_ONE_AUTHOR:9,
  HIERARCHY_TWO_AUTHOR:10,
  BREAKING_NEWS_AUTHOR:11,
};

export default availableDisplay;
